mix_classes = [
    "Genus Acrobeles",
    "Genus Acrobeloides",
    "Genus Amplimerlinius",
    "Genus Aphelenchoides",
    "Genus Aporcelaimus",
    "Genus Axonchium",
    "Genus Criconema",
    "Genus Criconemoides",
    "Genus Ditylenchus",
    "Genus Dorylaimus",
    "Genus Eudorylaimus",
    "Genus Helicotylenchus",
    "Genus Hemicycliophora",
    "Genus Hirschmaniella",
    "Genus Hoplolaimus",
    "Genus Meloidogyne",
    "Genus Mesodorylaimus",
    "Genus Miconchus",
    "Genus Mylonchulus",
    "Genus Panagrolaimus",
    "Genus Pratylenchus",
    "Genus Pristionchus",
    "Genus Radopholus",
    "Genus Rhabditis",
    "Genus Trichodorus",
    "Genus Xiphinema",
]

local_classes = [
    "Genus Criconema",
    "Genus Criconemoides",
    "Genus Helicotylenchus",
    "Genus Hemicycliophora",
    "Genus Hirschmaniella",
    "Genus Hoplolaimus",
    "Genus Meloidogyne",
    "Genus Pratylenchus",
    "Genus Radopholus",
    "Genus Trichodorus",
    "Genus Xiphinema",

]